[build]
command = "npm run build"
publish = ".site-build"

[functions]
directory = ".functions-build"
node_bundler = "esbuild"

[build.environment]
NODE_VERSION = "22"

[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "no-referrer"
